// Generated by generate-client from spec/openapi.json. Do not edit.

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  "audio-reels": (client, { params }) =>
    client.instagram.getAudioReels({
      audio_id: params.audio_id as string,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "basic-profile": (client, { params }) =>
    client.instagram.getBasicProfile({
      userId: params.userId as string,
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
    }),
  embed: (client, { params }) =>
    client.instagram.getEmbed({
      handle: params.handle as string,
    }),
  "highlight-detail": (client, { params }) =>
    client.instagram.getHighlightDetail({
      id: params.id as string,
    }),
  highlights: (client, { params }) =>
    client.instagram.getHighlights({
      ...(params.handle != null ? { handle: params.handle as string, user_id: params.user_id as (string | null) | undefined } : { handle: params.handle as (string | null) | undefined, user_id: params.user_id as string }),
    }),
  post: (client, { params }) =>
    client.instagram.getPost({
      url: params.url as string,
      region: params.region as (string | null) | undefined,
      trim: params.trim as boolean | undefined,
      download_media: params.download_media as (false | null) | undefined,
      include_play_count: params.include_play_count as boolean | undefined,
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
    }),
  "post-comments": (client, { params }) =>
    client.instagram.getPostComments({
      url: params.url as string,
      cursor: params.cursor as (string | null) | undefined,
      include_replies: params.include_replies as (false | null) | undefined,
    }),
  "post-count": (client, { params }) =>
    client.instagram.getPostCount({
      handle: params.handle as string,
      allow_estimated: params.allow_estimated as (boolean | null) | undefined,
    }),
  profile: (client, { params }) =>
    client.instagram.getProfile({
      handle: params.handle as string,
      trim: params.trim as boolean | undefined,
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
    }),
  "search-popular": (client, { params }) =>
    client.instagram.searchPopular({
      query: params.query as string,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "user-posts": (client, { params }) =>
    client.instagram.getUserPosts({
      handle: params.handle as string,
      next_max_id: params.next_max_id as (string | null) | undefined,
      trim: params.trim as boolean | undefined,
    }),
  "user-reels": (client, { params }) =>
    client.instagram.getUserReels({
      max_id: params.max_id as (string | null) | undefined,
      trim: params.trim as boolean | undefined,
      ...(params.handle != null ? { handle: params.handle as string, user_id: params.user_id as (string | null) | undefined } : { handle: params.handle as (string | null) | undefined, user_id: params.user_id as string }),
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
