// Generated by generate-client from spec/openapi.json. Do not edit.

import type { airbnb } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  calendar: (client, { body }) =>
    client.airbnb.getCalendar({
      count: body.count as number | undefined,
      currency: body.currency as string | undefined,
      month: body.month as number,
      room_id: body.room_id as string,
      year: body.year as number,
    }),
  details: (client, { body }) =>
    client.airbnb.getDetails({
      room_id: body.room_id as string,
    }),
  price: (client, { body }) =>
    client.airbnb.getPrice({
      adults: body.adults as number | undefined,
      check_in: body.check_in as string,
      check_out: body.check_out as string,
      currency: body.currency as string | undefined,
      room_id: body.room_id as string,
    }),
  reviews: (client, { body }) =>
    client.airbnb.getReviews({
      limit: body.limit as number | undefined,
      offset: body.offset as number | undefined,
      room_id: body.room_id as string,
      sort: body.sort as airbnb.ReviewSort | undefined,
    }),
  search: (client, { body }) =>
    client.airbnb.search({
      adults: body.adults as (number | null) | undefined,
      amenities: body.amenities as (airbnb.AmenityFilter[] | null) | undefined,
      check_in: body.check_in as (string | null) | undefined,
      check_out: body.check_out as (string | null) | undefined,
      children: body.children as (number | null) | undefined,
      currency: body.currency as string | undefined,
      cursor: body.cursor as string | undefined,
      free_cancellation: body.free_cancellation as boolean | undefined,
      infants: body.infants as (number | null) | undefined,
      lat: body.lat as (number | null) | undefined,
      lon: body.lon as (number | null) | undefined,
      min_bathrooms: body.min_bathrooms as (number | null) | undefined,
      min_bedrooms: body.min_bedrooms as (number | null) | undefined,
      min_beds: body.min_beds as (number | null) | undefined,
      ne_lat: body.ne_lat as (number | null) | undefined,
      ne_long: body.ne_long as (number | null) | undefined,
      place_id: body.place_id as (string | null) | undefined,
      price_max: body.price_max as (number | null) | undefined,
      price_min: body.price_min as (number | null) | undefined,
      query: body.query as (string | null) | undefined,
      radius_km: body.radius_km as (number | null) | undefined,
      sw_lat: body.sw_lat as (number | null) | undefined,
      sw_long: body.sw_long as (number | null) | undefined,
      zoom: body.zoom as (number | null) | undefined,
    }),
  "search-locations": (client, { params }) =>
    client.airbnb.searchLocations({
      query: params.query as string,
      language: params.language as string | undefined,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
