// Generated by generate-client from spec/openapi.json. Do not edit.

import type { goplus } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  "evm-token-security": (client, { params }) =>
    client.goplus.getEvmTokenSecurity({
      chain_id: params.chain_id as goplus.GoplusChainId,
      address: params.address as string,
    }),
  "solana-token-security": (client, { params }) =>
    client.goplus.getSolanaTokenSecurity({
      mint: params.mint as string,
    }),
  "tron-token-security": (client, { params }) =>
    client.goplus.getTronTokenSecurity({
      address: params.address as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
