// Generated by generate-client from spec/openapi.json. Do not edit.

import type { CommandSpec } from '../../runtime/types.js';

export const COMMANDS: CommandSpec[] = [
  {
    name: "evm-token-security",
    method: "get_evm_token_security",
    summary: "GoPlus token security for one EVM token: honeypot, tax, owner and mint flags, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` (1 complete, 2 partial, 3 no contract code) and `result`, which is keyed by the lowercased address. Powered by GoPlus Security.",
    credits: null,
    route: "GET /api/v1/goplus/evm/{chain_id}/tokens/{address}/security",
    hasBody: false,
    params: [
      { name: "chain_id", flag: "chain-id", in: "path", kind: "string", list: false, required: true, positional: true, choices: ["1", "56", "8453", "4663"], description: "EVM chain id: 1 Ethereum, 56 BNB Chain, 8453 Base, 4663 Robinhood Chain." },
      { name: "address", flag: "address", in: "path", kind: "string", list: false, required: true, positional: true, description: "Token contract address: 0x plus 40 hex characters, any case." },
    ],
  },
  {
    name: "solana-token-security",
    method: "get_solana_token_security",
    summary: "GoPlus token security for one Solana mint: mint, freeze, close and metadata authorities, Token-2022 transfer fee and hook, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` and `result`, which is keyed by the mint. Powered by GoPlus Security.",
    credits: null,
    route: "GET /api/v1/goplus/solana/tokens/{mint}/security",
    hasBody: false,
    params: [
      { name: "mint", flag: "mint", in: "path", kind: "string", list: false, required: true, positional: true, description: "Token mint address, base58." },
    ],
  },
];
