// Generated by generate-client from spec/openapi.json. Do not edit.

import type { gmgn } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  "activity-rank-info": (client, { params }) =>
    client.gmgn.activityRankInfo({
      chain: params.chain as gmgn.Chain,
    }),
  "agged-token-trades": (client, { params }) =>
    client.gmgn.aggedTokenTrades({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      period: params.period as gmgn.AggedTradePeriod | undefined,
      tag: params.tag as (gmgn.AggedTradeTag | null) | undefined,
    }),
  "agged-token-transfers": (client, { params }) =>
    client.gmgn.aggedTokenTransfers({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      wallet_address: params.wallet_address as string,
      period: params.period as gmgn.AggedTradePeriod | undefined,
    }),
  "bluechip-rank": (client, { params }) =>
    client.gmgn.bluechipRank({
      chain: params.chain as gmgn.Chain,
      interval: params.interval as gmgn.TrendingInterval | undefined,
      limit: params.limit as number | undefined,
      filters: params.filters as (gmgn.TokenFilter[] | null) | undefined,
    }),
  "dev-created-tokens": (client, { params }) =>
    client.gmgn.devCreatedTokens({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
    }),
  "dex-trades-polling": (client, { params }) =>
    client.gmgn.dexTradesPolling({
      chain: params.chain as gmgn.Chain,
      window: params.window as gmgn.TimeWindow | undefined,
    }),
  "gas-price-list": (client) =>
    client.gmgn.gasPriceList(),
  "holder-stat": (client, { params }) =>
    client.gmgn.holderStat({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  holders: (client, { params }) =>
    client.gmgn.holders({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      limit: params.limit as number | undefined,
      cost: params.cost as number | undefined,
      order_by: params.order_by as gmgn.HolderOrderBy | undefined,
      direction: params.direction as gmgn.SortDirection | undefined,
      tag: params.tag as (gmgn.HolderTag | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "hot-searches": (client, { body }) =>
    client.gmgn.hotSearches({
      requests: body.requests as gmgn.TrendingChainRequest[],
    }),
  "launchpad-tax-policy": (client, { params }) =>
    client.gmgn.launchpadTaxPolicy({
      chain: params.chain as gmgn.Chain,
    }),
  liquidity: (client, { params }) =>
    client.gmgn.liquidity({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "live-preview": (client, { params }) =>
    client.gmgn.livePreview({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "live-twitch-kol": (client) =>
    client.gmgn.liveTwitchKol(),
  "major-coin-prices": (client, { body }) =>
    client.gmgn.majorCoinPrices({
      symbols: body.symbols as string[],
    }),
  "mcap-candles": (client, { params }) =>
    client.gmgn.mcapCandles({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      resolution: params.resolution as gmgn.Resolution | undefined,
      limit: params.limit as number | undefined,
    }),
  "multi-token-full-info": (client, { params, body }) =>
    client.gmgn.multiTokenFullInfo({
      chain: params.chain as gmgn.Chain,
    }, {
      addresses: body.addresses as string[],
    }),
  "multi-token-info": (client, { params, body }) =>
    client.gmgn.multiTokenInfo({
      chain: params.chain as gmgn.Chain,
    }, {
      addresses: body.addresses as string[],
    }),
  "multi-window-token-info": (client, { params, body }) =>
    client.gmgn.multiWindowTokenInfo({
      chain: params.chain as gmgn.Chain,
    }, {
      addresses: body.addresses as string[],
    }),
  "native-transfer": (client, { params }) =>
    client.gmgn.nativeTransfer({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
    }),
  "new-pairs": (client, { params }) =>
    client.gmgn.newPairs({
      chain: params.chain as gmgn.Chain,
      interval: params.interval as gmgn.TrendingInterval | undefined,
      limit: params.limit as number | undefined,
      order_by: params.order_by as gmgn.NewPairsOrderBy | undefined,
      filters: params.filters as (gmgn.TokenFilter[] | null) | undefined,
      launchpad_platforms: params.launchpad_platforms as (string[] | null) | undefined,
    }),
  "pool-fee-info": (client, { params }) =>
    client.gmgn.poolFeeInfo({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "recommend-slippage": (client, { params }) =>
    client.gmgn.recommendSlippage({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  search: (client, { params }) =>
    client.gmgn.search({
      chain: params.chain as gmgn.Chain,
      q: params.q as string,
    }),
  security: (client, { params }) =>
    client.gmgn.security({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "similar-coin-extremes": (client, { params }) =>
    client.gmgn.similarCoinExtremes({
      chain: params.chain as gmgn.Chain,
      symbol: params.symbol as string,
      name: params.name as string,
      token_address: params.token_address as string,
    }),
  "similar-coins": (client, { params }) =>
    client.gmgn.similarCoins({
      chain: params.chain as gmgn.Chain,
      symbol: params.symbol as string,
      name: params.name as string,
      token_address: params.token_address as string,
      order_by: params.order_by as gmgn.SimilarCoinsOrderBy | undefined,
    }),
  "smart-money-wallet-info": (client, { params }) =>
    client.gmgn.smartMoneyWalletInfo({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
    }),
  socials: (client, { params }) =>
    client.gmgn.socials({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  stats: (client, { params }) =>
    client.gmgn.stats({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "swap-rankings": (client, { params }) =>
    client.gmgn.swapRankings({
      chain: params.chain as gmgn.Chain,
      timeframe: params.timeframe as gmgn.TimeWindow | undefined,
      platforms: params.platforms as (string[] | null) | undefined,
    }),
  "token-ai-narrative": (client, { params }) =>
    client.gmgn.tokenAiNarrative({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-bundler-stat": (client, { params }) =>
    client.gmgn.tokenBundlerStat({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-candles": (client, { params }) =>
    client.gmgn.tokenCandles({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      resolution: params.resolution as gmgn.Resolution | undefined,
      from_timestamp: params.from_timestamp as number | undefined,
      to_timestamp: params.to_timestamp as (number | null) | undefined,
      limit: params.limit as number | undefined,
    }),
  "token-community-messages": (client, { params }) =>
    client.gmgn.tokenCommunityMessages({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      limit: params.limit as number | undefined,
    }),
  "token-dev-info": (client, { params }) =>
    client.gmgn.tokenDevInfo({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-fee-distribution": (client, { params }) =>
    client.gmgn.tokenFeeDistribution({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-fee-info": (client, { params }) =>
    client.gmgn.tokenFeeInfo({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-holder-extra-info": (client, { params }) =>
    client.gmgn.tokenHolderExtraInfo({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      wallet_addresses: params.wallet_addresses as string[],
    }),
  "token-info-brief": (client, { params, body }) =>
    client.gmgn.tokenInfoBrief({
      chain: params.chain as gmgn.Chain,
    }, {
      addresses: body.addresses as string[],
    }),
  "token-liquidity-stats": (client, { params }) =>
    client.gmgn.tokenLiquidityStats({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-liquidity-trend": (client, { params }) =>
    client.gmgn.tokenLiquidityTrend({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-logo-history": (client, { params }) =>
    client.gmgn.tokenLogoHistory({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "token-prices": (client, { params, body }) =>
    client.gmgn.tokenPrices({
      chain: params.chain as gmgn.Chain,
    }, {
      addresses: body.addresses as string[],
    }),
  "token-signals": (client, { params, body }) =>
    client.gmgn.tokenSignals({
      chain: params.chain as gmgn.Chain,
    }, {
      groups: body.groups as gmgn.TokenSignalGroupRequest[],
    }),
  "token-trades-v2": (client, { params }) =>
    client.gmgn.tokenTradesV2({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      maker: params.maker as string | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "token-trends": (client, { params }) =>
    client.gmgn.tokenTrends({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      trends_types: params.trends_types as gmgn.TokenTrendsType[] | undefined,
    }),
  "top-buyers": (client, { params }) =>
    client.gmgn.topBuyers({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "top-callers": (client, { params }) =>
    client.gmgn.topCallers({
      chain: params.chain as gmgn.Chain,
      window: params.window as gmgn.TimeWindow | undefined,
    }),
  "trader-stat": (client, { params }) =>
    client.gmgn.traderStat({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  traders: (client, { params }) =>
    client.gmgn.traders({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      limit: params.limit as number | undefined,
      order_by: params.order_by as gmgn.TraderOrderBy | undefined,
      direction: params.direction as gmgn.SortDirection | undefined,
      tag: params.tag as (gmgn.HolderTag | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  trades: (client, { params }) =>
    client.gmgn.trades({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
      maker: params.maker as string | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "trending-tokens": (client, { body }) =>
    client.gmgn.trendingTokens({
      requests: body.requests as gmgn.TrendingChainRequest[],
    }),
  "wallet-activity": (client, { params }) =>
    client.gmgn.walletActivity({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
      limit: params.limit as number | undefined,
      type: params.type as (string[] | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "wallet-chain-balances": (client, { params }) =>
    client.gmgn.walletChainBalances({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
    }),
  "wallet-common-stat": (client, { params }) =>
    client.gmgn.walletCommonStat({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
    }),
  "wallet-pnl": (client, { params }) =>
    client.gmgn.walletPnl({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
      period: params.period as gmgn.WalletRankPeriod | undefined,
    }),
  "wallet-rankings": (client, { params }) =>
    client.gmgn.walletRankings({
      chain: params.chain as gmgn.Chain,
      period: params.period as gmgn.WalletRankPeriod | undefined,
      order_by: params.order_by as gmgn.WalletRankOrderBy | undefined,
    }),
  "wallet-stat": (client, { params }) =>
    client.gmgn.walletStat({
      chain: params.chain as gmgn.Chain,
      wallet_address: params.wallet_address as string,
      period: params.period as (gmgn.WalletStatPeriod | null) | undefined,
    }),
  "wallet-tags-stat": (client, { params }) =>
    client.gmgn.walletTagsStat({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
  "website-info": (client, { params }) =>
    client.gmgn.websiteInfo({
      chain: params.chain as gmgn.Chain,
      token_address: params.token_address as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
