// Generated by generate-client from spec/openapi.json. Do not edit.

import type { tiktok } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  "collection-videos": (client, { params }) =>
    client.tiktok.getCollectionVideos({
      cursor: params.cursor as (string | null) | undefined,
      url: params.url as string,
    }),
  "comment-replies": (client, { params }) =>
    client.tiktok.getCommentReplies({
      comment_id: params.comment_id as string,
      cursor: params.cursor as (number | null) | undefined,
      url: params.url as string,
    }),
  comments: (client, { params }) =>
    client.tiktok.getComments({
      cursor: params.cursor as (number | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
      url: params.url as string,
    }),
  followers: (client, { params }) =>
    client.tiktok.getFollowers({
      min_time: params.min_time as (number | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
      handle: params.handle as (string | null) | undefined,
      user_id: params.user_id as (string | null) | undefined,
    }),
  following: (client, { params }) =>
    client.tiktok.getFollowing({
      handle: params.handle as string,
      min_time: params.min_time as (number | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
    }),
  profile: (client, { params }) =>
    client.tiktok.getProfile({
      cache_max_age: params.cache_max_age as (tiktok.GetProfileParamsCacheMaxAge | null) | undefined,
      handle: params.handle as (string | null) | undefined,
      user_id: params.user_id as (string | null) | undefined,
    }),
  "profile-videos": (client, { params }) =>
    client.tiktok.getProfileVideos({
      sort_by: params.sort_by as (tiktok.GetProfileVideosParamsSortBy | null) | undefined,
      max_cursor: params.max_cursor as (string | null) | undefined,
      region: params.region as (string | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
      handle: params.handle as (string | null) | undefined,
      user_id: params.user_id as (string | null) | undefined,
    }),
  "search-hashtag": (client, { params }) =>
    client.tiktok.searchHashtag({
      hashtag: params.hashtag as string,
      region: params.region as (string | null) | undefined,
      cursor: params.cursor as (number | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
    }),
  "search-suggestions": (client, { params }) =>
    client.tiktok.getSearchSuggestions({
      query: params.query as string,
      region: params.region as (string | null) | undefined,
    }),
  song: (client, { params }) =>
    client.tiktok.getSong({
      clipId: params.clipId as string,
    }),
  "song-videos": (client, { params }) =>
    client.tiktok.getSongVideos({
      clipId: params.clipId as string,
      cursor: params.cursor as (number | null) | undefined,
    }),
  transcript: (client, { params }) =>
    client.tiktok.getTranscript({
      language: params.language as (string | null) | undefined,
      use_ai_as_fallback: params.use_ai_as_fallback as (boolean | null) | undefined,
      url: params.url as string,
    }),
  "trending-feed": (client, { params }) =>
    client.tiktok.getTrendingFeed({
      region: params.region as string,
      trim: params.trim as (boolean | null) | undefined,
    }),
  video: (client, { params }) =>
    client.tiktok.getVideo({
      get_transcript: params.get_transcript as (boolean | null) | undefined,
      region: params.region as (string | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
      cache_max_age: params.cache_max_age as (tiktok.GetVideoParamsCacheMaxAge | null) | undefined,
      url: params.url as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
