// Generated by generate-client from spec/openapi.json. Do not edit.

import { COMMANDS } from '../src/services/pumpfun/spec.js';
import { checkCapturedRequests } from './captured-requests.js';

checkCapturedRequests('pumpfun', COMMANDS);
