// Generated by generate-client from spec/openapi.json. Do not edit.

import { COMMANDS } from '../src/services/pinterest/spec.js';
import { checkCapturedRequests } from './captured-requests.js';

checkCapturedRequests('pinterest', COMMANDS);
