// Generated by generate-client from spec/openapi.json. Do not edit.

import { COMMANDS } from '../src/services/instagram/spec.js';
import { checkCapturedRequests } from './captured-requests.js';

checkCapturedRequests('instagram', COMMANDS);
