// Generated by generate-client from spec/openapi.json. Do not edit.

import { COMMANDS } from '../src/services/twitter/spec.js';
import { checkCapturedRequests } from './captured-requests.js';

checkCapturedRequests('twitter', COMMANDS);
