// Generated by generate-client from spec/openapi.json. Do not edit.

import { COMMANDS } from '../src/services/geckoterminal/spec.js';
import { checkCapturedRequests } from './captured-requests.js';

checkCapturedRequests('geckoterminal', COMMANDS);
