// Generated by generate-client from spec/openapi.json. Do not edit.

import type { geckoterminal } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  candlesticks: (client, { params }) =>
    client.geckoterminal.candlesticks({
      pool_id: params.pool_id as string,
      pair_id: params.pair_id as string,
      from_timestamp: params.from_timestamp as number,
      to_timestamp: params.to_timestamp as number,
      resolution: params.resolution as geckoterminal.CandlestickResolution | undefined,
      currency: params.currency as geckoterminal.CandlestickCurrency | undefined,
      is_inverted: params.is_inverted as boolean | undefined,
    }),
  dexes: (client, { params }) =>
    client.geckoterminal.dexes({
      network: params.network as (string | null) | undefined,
      page: params.page as (number | null) | undefined,
    }),
  "global-stats": (client) =>
    client.geckoterminal.globalStats(),
  "latest-pools": (client, { params }) =>
    client.geckoterminal.latestPools({
      page: params.page as number | undefined,
      pool_creation_hours_ago_lte: params.pool_creation_hours_ago_lte as number | undefined,
    }),
  "network-latest-pools": (client, { params }) =>
    client.geckoterminal.networkLatestPools({
      network: params.network as string,
      page: params.page as number | undefined,
      pool_creation_hours_ago_lte: params.pool_creation_hours_ago_lte as number | undefined,
    }),
  "network-pools": (client, { params, body }) =>
    client.geckoterminal.networkPools({
      network: params.network as string,
    }, {
      buy_tax: body.buy_tax as (geckoterminal.RangeFilter | null) | undefined,
      buys: body.buys as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      dex: body.dex as (string | null) | undefined,
      dexes: body.dexes as (string[] | null) | undefined,
      fdv_in_usd: body.fdv_in_usd as (geckoterminal.RangeFilter | null) | undefined,
      good_gt_score: body.good_gt_score as (boolean | null) | undefined,
      has_social: body.has_social as (boolean | null) | undefined,
      holder_count: body.holder_count as (geckoterminal.RangeFilter | null) | undefined,
      liquidity: body.liquidity as (geckoterminal.RangeFilter | null) | undefined,
      mc_in_usd: body.mc_in_usd as (geckoterminal.RangeFilter | null) | undefined,
      networks: body.networks as (string[] | null) | undefined,
      no_honeypot: body.no_honeypot as (boolean | null) | undefined,
      on_coingecko: body.on_coingecko as (boolean | null) | undefined,
      page: body.page as number | undefined,
      pool_creation_hours_ago: body.pool_creation_hours_ago as (geckoterminal.RangeFilter | null) | undefined,
      sell_tax: body.sell_tax as (geckoterminal.RangeFilter | null) | undefined,
      sells: body.sells as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      sort: body.sort as (geckoterminal.PoolSort | null) | undefined,
      top_10_holders_percentage: body.top_10_holders_percentage as (geckoterminal.RangeFilter | null) | undefined,
      tx_count: body.tx_count as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      volume_24h: body.volume_24h as (geckoterminal.RangeFilter | null) | undefined,
    }),
  "network-rankings": (client, { params }) =>
    client.geckoterminal.networkRankings({
      page: params.page as number | undefined,
    }),
  networks: (client, { params }) =>
    client.geckoterminal.networks({
      sort: params.sort as (string | null) | undefined,
    }),
  pool: (client, { params }) =>
    client.geckoterminal.pool({
      network: params.network as string,
      address: params.address as string,
      base_token: params.base_token as number | undefined,
    }),
  "pool-related-pools": (client, { params }) =>
    client.geckoterminal.poolRelatedPools({
      network: params.network as string,
      address: params.address as string,
    }),
  "pool-sender-swaps": (client, { params }) =>
    client.geckoterminal.poolSenderSwaps({
      network: params.network as string,
      address: params.address as string,
      from_timestamp: params.from_timestamp as number,
      to_timestamp: params.to_timestamp as number,
      pair_id: params.pair_id as string,
      sender: params.sender as (string | null) | undefined,
      include_developer: params.include_developer as boolean | undefined,
      inverted: params.inverted as boolean | undefined,
    }),
  "pool-swaps": (client, { params }) =>
    client.geckoterminal.poolSwaps({
      network: params.network as string,
      address: params.address as string,
      pair_id: params.pair_id as string,
      page_after: params.page_after as (string | null) | undefined,
      page_before: params.page_before as (string | null) | undefined,
      inverted: params.inverted as boolean | undefined,
      sender: params.sender as (string | null) | undefined,
    }),
  "pool-token-info-snapshots": (client, { params }) =>
    client.geckoterminal.poolTokenInfoSnapshots({
      network: params.network as string,
      address: params.address as string,
    }),
  pools: (client, { body }) =>
    client.geckoterminal.pools({
      buy_tax: body.buy_tax as (geckoterminal.RangeFilter | null) | undefined,
      buys: body.buys as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      dexes: body.dexes as (string[] | null) | undefined,
      fdv_in_usd: body.fdv_in_usd as (geckoterminal.RangeFilter | null) | undefined,
      good_gt_score: body.good_gt_score as (boolean | null) | undefined,
      has_social: body.has_social as (boolean | null) | undefined,
      holder_count: body.holder_count as (geckoterminal.RangeFilter | null) | undefined,
      liquidity: body.liquidity as (geckoterminal.RangeFilter | null) | undefined,
      mc_in_usd: body.mc_in_usd as (geckoterminal.RangeFilter | null) | undefined,
      networks: body.networks as (string[] | null) | undefined,
      no_honeypot: body.no_honeypot as (boolean | null) | undefined,
      on_coingecko: body.on_coingecko as (boolean | null) | undefined,
      page: body.page as number | undefined,
      pool_creation_hours_ago: body.pool_creation_hours_ago as (geckoterminal.RangeFilter | null) | undefined,
      sell_tax: body.sell_tax as (geckoterminal.RangeFilter | null) | undefined,
      sells: body.sells as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      sort: body.sort as (geckoterminal.PoolSort | null) | undefined,
      top_10_holders_percentage: body.top_10_holders_percentage as (geckoterminal.RangeFilter | null) | undefined,
      tx_count: body.tx_count as (geckoterminal.TimeframedRangeFilter | null) | undefined,
      volume_24h: body.volume_24h as (geckoterminal.RangeFilter | null) | undefined,
    }),
  "revival-radar-pools": (client) =>
    client.geckoterminal.revivalRadarPools(),
  search: (client, { params }) =>
    client.geckoterminal.search({
      query: params.query as string,
    }),
  "search-trends": (client) =>
    client.geckoterminal.searchTrends(),
  "tag-network-pools": (client, { params }) =>
    client.geckoterminal.tagNetworkPools({
      tag: params.tag as string,
      network: params.network as string,
      page: params.page as number | undefined,
    }),
  "tag-pools": (client, { params }) =>
    client.geckoterminal.tagPools({
      tag: params.tag as string,
      page: params.page as number | undefined,
    }),
  tags: (client, { params }) =>
    client.geckoterminal.tags({
      page: params.page as number | undefined,
    }),
  "token-developer-past-tokens": (client, { params }) =>
    client.geckoterminal.tokenDeveloperPastTokens({
      developer_detail_id: params.developer_detail_id as string,
    }),
  "token-historical-holders": (client, { params }) =>
    client.geckoterminal.tokenHistoricalHolders({
      network: params.network as string,
      token_address: params.token_address as string,
      period: params.period as geckoterminal.HolderHistoryPeriod | undefined,
    }),
  "token-top-holders": (client, { params }) =>
    client.geckoterminal.tokenTopHolders({
      network: params.network as string,
      token_address: params.token_address as string,
    }),
  "token-top-traders": (client, { params }) =>
    client.geckoterminal.tokenTopTraders({
      token_id: params.token_id as string,
    }),
  "trending-links": (client) =>
    client.geckoterminal.trendingLinks(),
  "trending-themes": (client, { params }) =>
    client.geckoterminal.trendingThemes({
      network: params.network as (string | null) | undefined,
      dex: params.dex as (string | null) | undefined,
      more_themes: params.more_themes as boolean | undefined,
    }),
  trends: (client, { params }) =>
    client.geckoterminal.trends({
      network: params.network as (string | null) | undefined,
      dex: params.dex as (string | null) | undefined,
    }),
  "wallet-token": (client, { params }) =>
    client.geckoterminal.walletToken({
      token_id: params.token_id as string,
      wallet_address: params.wallet_address as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
