// Generated by generate-client from spec/openapi.json. Do not edit.

import type { youtube } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  channel: (client, { params }) =>
    client.youtube.getChannel({
      channel_id: params.channel_id as string,
    }),
  "channel-videos": (client, { params }) =>
    client.youtube.getChannelVideos({
      channel_id: params.channel_id as string,
      content_type: params.content_type as youtube.ChannelContentType | undefined,
      cursor: params.cursor as string | undefined,
    }),
  "comment-replies": (client, { params }) =>
    client.youtube.getCommentReplies({
      video_id: params.video_id as string,
      comment_id: params.comment_id as string,
      cursor: params.cursor as string,
    }),
  comments: (client, { params }) =>
    client.youtube.getComments({
      video_id: params.video_id as string,
      sort: params.sort as youtube.CommentSortOrder | undefined,
      cursor: params.cursor as string | undefined,
    }),
  formats: (client, { params }) =>
    client.youtube.getFormats({
      video_id: params.video_id as string,
    }),
  heatmap: (client, { params }) =>
    client.youtube.getHeatmap({
      video_id: params.video_id as string,
    }),
  metadata: (client, { params }) =>
    client.youtube.getMetadata({
      video_id: params.video_id as string,
      fields: params.fields as (string | null) | undefined,
      country: params.country as (string | null) | undefined,
    }),
  playlist: (client, { params }) =>
    client.youtube.getPlaylist({
      playlist_id: params.playlist_id as string,
      limit: params.limit as number | undefined,
    }),
  search: (client, { params }) =>
    client.youtube.search({
      query: params.query as string,
      country: params.country as (string | null) | undefined,
      sort: params.sort as youtube.SearchSort | undefined,
      upload_date: params.upload_date as (youtube.UploadDate | null) | undefined,
      search_type: params.search_type as (youtube.SearchType | null) | undefined,
      duration: params.duration as (youtube.VideoDuration | null) | undefined,
      features: params.features as (youtube.Feature[] | null) | undefined,
      cursor: params.cursor as string | undefined,
    }),
  "subtitle-tracks": (client, { params }) =>
    client.youtube.getSubtitleTracks({
      video_id: params.video_id as string,
      country: params.country as (string | null) | undefined,
    }),
  subtitles: (client, { params }) =>
    client.youtube.getSubtitles({
      video_id: params.video_id as string,
      language: params.language as string | undefined,
      subtitle_format: params.subtitle_format as youtube.SubtitleFormat | undefined,
      source: params.source as youtube.SubtitleSource | undefined,
      country: params.country as (string | null) | undefined,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
