// Generated by generate-client from spec/openapi.json. Do not edit.

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  community: (client, { params }) =>
    client.twitter.getCommunity({
      community_id: params.community_id as string,
    }),
  tweet: (client, { params }) =>
    client.twitter.getTweet({
      tweet_id: params.tweet_id as string,
    }),
  "user-profile": (client, { params }) =>
    client.twitter.getUserProfile({
      screen_name: params.screen_name as string,
    }),
  "user-profile-by-id": (client, { params }) =>
    client.twitter.getUserProfileById({
      user_id: params.user_id as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
