// Generated by generate-client from spec/openapi.json. Do not edit.

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  community: (client, { params }) =>
    client.twitter.getCommunity({
      url: params.url as string,
    }),
  "community-tweets": (client, { params }) =>
    client.twitter.getCommunityTweets({
      url: params.url as string,
    }),
  profile: (client, { params }) =>
    client.twitter.getProfile({
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
      handle: params.handle as (string | null) | undefined,
      user_id: params.user_id as (string | null) | undefined,
    }),
  tweet: (client, { params }) =>
    client.twitter.getTweet({
      url: params.url as string,
      trim: params.trim as (boolean | null) | undefined,
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
    }),
  "user-tweets": (client, { params }) =>
    client.twitter.getUserTweets({
      handle: params.handle as string,
      trim: params.trim as (boolean | null) | undefined,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
