// Generated by generate-client from spec/openapi.json. Do not edit.

import type { ponsfamily } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  analytics: (client) =>
    client.ponsfamily.getAnalytics(),
  "creator-holdings": (client, { body }) =>
    client.ponsfamily.getCreatorHoldings({
      pairs: body.pairs as ponsfamily.CreatorHoldingPair[],
    }),
  "developer-trades": (client, { params }) =>
    client.ponsfamily.getDeveloperTrades({
      token: params.token as string,
      deployer: params.deployer as string,
    }),
  "eth-price": (client) =>
    client.ponsfamily.getEthPrice(),
  "fee-sharing": (client, { params }) =>
    client.ponsfamily.getFeeSharing({
      tokens: params.tokens as string[],
    }),
  "forum-community": (client, { params }) =>
    client.ponsfamily.getForumCommunity({
      slug: params.slug as string,
    }),
  "forum-holding": (client, { params }) =>
    client.ponsfamily.getForumHolding({
      token: params.token as string,
      wallet: params.wallet as string,
    }),
  "forum-market": (client) =>
    client.ponsfamily.getForumMarket(),
  "forum-post": (client, { params }) =>
    client.ponsfamily.getForumPost({
      post_id: params.post_id as string,
    }),
  "forum-post-comments": (client, { params }) =>
    client.ponsfamily.getForumPostComments({
      post_id: params.post_id as string,
      sort: params.sort as ponsfamily.PostSort | undefined,
    }),
  "list-cto-migrations": (client) =>
    client.ponsfamily.listCtoMigrations(),
  "list-forum-communities": (client, { params }) =>
    client.ponsfamily.listForumCommunities({
      rank: params.rank as ponsfamily.CommunityRank | undefined,
      limit: params.limit as number | undefined,
    }),
  "list-forum-posts": (client, { params }) =>
    client.ponsfamily.listForumPosts({
      sort: params.sort as ponsfamily.PostSort | undefined,
      community: params.community as (string | null) | undefined,
    }),
  "list-graduated-catalog": (client) =>
    client.ponsfamily.listGraduatedCatalog(),
  "list-graduations": (client) =>
    client.ponsfamily.listGraduations(),
  "list-launches": (client, { params }) =>
    client.ponsfamily.listLaunches({
      sort: params.sort as ponsfamily.LaunchSort | undefined,
      age: params.age as ponsfamily.LaunchAge | undefined,
      version: params.version as ponsfamily.LaunchVersion | undefined,
      page: params.page as number | undefined,
      page_size: params.page_size as number | undefined,
      include_graduated: params.include_graduated as boolean | undefined,
      graduated_page: params.graduated_page as number | undefined,
      graduated_page_size: params.graduated_page_size as number | undefined,
    }),
  "list-live-markets": (client, { params }) =>
    client.ponsfamily.listLiveMarkets({
      markets: params.markets as (string[] | null) | undefined,
    }),
  market: (client, { params }) =>
    client.ponsfamily.getMarket({
      token: params.token as string,
      include_holders: params.include_holders as boolean | undefined,
    }),
  "market-ath": (client, { params }) =>
    client.ponsfamily.getMarketAth({
      token: params.token as string,
    }),
  "market-burned": (client, { params }) =>
    client.ponsfamily.getMarketBurned({
      token: params.token as string,
    }),
  "market-chart": (client, { params }) =>
    client.ponsfamily.getMarketChart({
      token: params.token as string,
      range: params.range as ponsfamily.ChartRange | undefined,
    }),
  "market-holders": (client, { params }) =>
    client.ponsfamily.getMarketHolders({
      token: params.token as string,
    }),
  "market-order-depth": (client, { params }) =>
    client.ponsfamily.getMarketOrderDepth({
      token: params.token as string,
    }),
  "market-tip": (client, { params }) =>
    client.ponsfamily.getMarketTip({
      token: params.token as string,
    }),
  "market-trades": (client, { params }) =>
    client.ponsfamily.getMarketTrades({
      token: params.token as string,
    }),
  "portfolio-chart": (client, { params }) =>
    client.ponsfamily.getPortfolioChart({
      address: params.address as string,
      range: params.range as ponsfamily.PortfolioRange | undefined,
    }),
  profile: (client, { params }) =>
    client.ponsfamily.getProfile({
      address: params.address as string,
    }),
  "search-launches": (client, { params }) =>
    client.ponsfamily.searchLaunches({
      q: params.q as string | undefined,
      sort: params.sort as ponsfamily.LaunchSearchSort | undefined,
      age: params.age as ponsfamily.LaunchAge | undefined,
      page: params.page as number | undefined,
    }),
  token: (client, { params }) =>
    client.ponsfamily.getToken({
      token: params.token as string,
    }),
  "token-images": (client, { params }) =>
    client.ponsfamily.getTokenImages({
      tokens: params.tokens as string[],
    }),
  "v2-creator-fees": (client, { params }) =>
    client.ponsfamily.getV2CreatorFees({
      token: params.token as string,
    }),
  "v2-distributor": (client, { params }) =>
    client.ponsfamily.getV2Distributor({
      token: params.token as string,
    }),
  "v2-market-chart": (client, { params }) =>
    client.ponsfamily.getV2MarketChart({
      token: params.token as string,
      range: params.range as ponsfamily.ChartRange | undefined,
    }),
  "v2-market-holders": (client, { params }) =>
    client.ponsfamily.getV2MarketHolders({
      token: params.token as string,
    }),
  "v2-market-trades": (client, { params }) =>
    client.ponsfamily.getV2MarketTrades({
      token: params.token as string,
    }),
  "wallet-identities": (client, { params }) =>
    client.ponsfamily.getWalletIdentities({
      addresses: params.addresses as string[],
    }),
  "wallet-positions": (client, { params }) =>
    client.ponsfamily.getWalletPositions({
      address: params.address as string,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
