// Generated by generate-client from spec/openapi.json. Do not edit.

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  board: (client, { params }) =>
    client.pinterest.getBoard({
      cursor: params.cursor as (string | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
      url: params.url as string,
    }),
  pin: (client, { params }) =>
    client.pinterest.getPin({
      trim: params.trim as (boolean | null) | undefined,
      cache_max_age: params.cache_max_age as ("1d" | "3d" | "7d" | "14d" | "30d" | null) | undefined,
      url: params.url as string,
    }),
  "search-pins": (client, { params }) =>
    client.pinterest.searchPins({
      query: params.query as string,
      cursor: params.cursor as (string | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
    }),
  "user-boards": (client, { params }) =>
    client.pinterest.getUserBoards({
      handle: params.handle as string,
      cursor: params.cursor as (string | null) | undefined,
      trim: params.trim as (boolean | null) | undefined,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
