// Generated by generate-client from spec/openapi.json. Do not edit.

import type { CommandSpec } from '../../runtime/types.js';

export const COMMANDS: CommandSpec[] = [
  {
    name: "board",
    method: "get_board",
    summary: "The pins on a public Pinterest board, in board order: Pinterest's own pin objects with images, link, title, pinner, board and aggregated pin data. `id` is the numeric pin id, `link` is `null` on a pin uploaded without one, and Pinterest sends no `pin_join` for board pins. About 25 pins per page; pass `cursor` back for the next page, which is `null` on the last one.",
    credits: 1,
    route: "GET /v1/pinterest/board",
    hasBody: false,
    pagination: { flag: "cursor", nextPath: "cursor" },
    params: [
      { name: "cursor", flag: "cursor", in: "query", kind: "string", list: false, required: false, positional: false, description: "The `cursor` from the previous page. Omit it, or send it empty, for the first page." },
      { name: "trim", flag: "trim", in: "query", kind: "boolean", list: false, required: false, positional: false, description: "Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body." },
      { name: "url", flag: "url", in: "query", kind: "string", list: false, required: true, positional: true, description: "A Pinterest board URL: `https://www.pinterest.com/<username>/<board>/` on any Pinterest domain, or the relative `/<username>/<board>/` that `/user/boards` returns as `url`." },
    ],
  },
  {
    name: "pin",
    method: "get_pin",
    summary: "One Pinterest pin: title, description, link, dominant color, pinner and origin pinner, board, images at every size (`images_<size>` and `imageSpec_<size>`), counts, video variants and annotations. The fields are Pinterest's own, in camelCase, merged from the two queries the pin page runs, matching Scrape Creators' provider-data fields but omitting its top-level status and credit metadata. `entityId` is the numeric pin id and `id` is Pinterest's node id. Pinterest's `isVideo` is `false` on some video pins; `videos` is set on every one. Accepts pin URLs on any Pinterest domain and pin.it share links.",
    credits: 1,
    route: "GET /v1/pinterest/pin",
    hasBody: false,
    params: [
      { name: "trim", flag: "trim", in: "query", kind: "boolean", list: false, required: false, positional: false, description: "Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body." },
      { name: "cache_max_age", flag: "cache-max-age", in: "query", kind: "string", list: false, required: false, positional: false, choices: ["1d", "3d", "7d", "14d", "30d"], description: "Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged." },
      { name: "url", flag: "url", in: "query", kind: "string", list: false, required: true, positional: true, description: "A Pinterest pin URL: `https://www.pinterest.com/pin/<id>/` on any Pinterest domain, the long form with a title (`/pin/<title>--<id>/`), or a `https://pin.it/<code>` share link." },
    ],
  },
  {
    name: "search-pins",
    method: "search_pins",
    summary: "Searches Pinterest pins. Each pin is Pinterest's own search result object plus a `url`, the same provider-data fields Scrape Creators returns, without Scrape Creators' top-level status and credit metadata. `id` is the numeric pin id; a pin uploaded without a link has no `link` key. Pinterest sends up to 25 pins per page and the count varies, so keep paging while `cursor` is not `null`; a pin can repeat across pages. Pinterest matches loosely, so most queries return related pins, but a query with no matches answers an empty page, which is charged.",
    credits: 1,
    route: "GET /v1/pinterest/search",
    hasBody: false,
    pagination: { flag: "cursor", nextPath: "cursor" },
    params: [
      { name: "query", flag: "query", in: "query", kind: "string", list: false, required: true, positional: true, description: "What to search Pinterest pins for." },
      { name: "cursor", flag: "cursor", in: "query", kind: "string", list: false, required: false, positional: false, description: "The `cursor` from the previous page. Omit it, or send it empty, for the first page." },
      { name: "trim", flag: "trim", in: "query", kind: "boolean", list: false, required: false, positional: false, description: "Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body." },
    ],
  },
  {
    name: "user-boards",
    method: "get_user_boards",
    summary: "A Pinterest user's public boards, most recently pinned to first: name, URL, description, pin and follower counts, owner and cover images. About 25 boards per page; pass `cursor` back for the next page, which is `null` on the last one.",
    credits: 1,
    route: "GET /v1/pinterest/user/boards",
    hasBody: false,
    pagination: { flag: "cursor", nextPath: "cursor" },
    params: [
      { name: "handle", flag: "handle", in: "query", kind: "string", list: false, required: true, positional: true, description: "The Pinterest username, with or without a leading @." },
      { name: "cursor", flag: "cursor", in: "query", kind: "string", list: false, required: false, positional: false, description: "The `cursor` from the previous page. Omit it, or send it empty, for the first page." },
      { name: "trim", flag: "trim", in: "query", kind: "boolean", list: false, required: false, positional: false, description: "Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body." },
    ],
  },
];
