// Generated by generate-client from spec/openapi.json. Do not edit.

import type { pumpfun } from '@tapline/client';

import type { Command } from '../../runtime/types.js';
import { COMMANDS } from './spec.js';

const RUNNERS: Record<string, Command['run']> = {
  "achievement-catalog": (client) =>
    client.pumpfun.achievementCatalog(),
  "approved-creator": (client, { params }) =>
    client.pumpfun.approvedCreator({
      mint: params.mint as string,
    }),
  ath: (client, { params }) =>
    client.pumpfun.ath({
      mint: params.mint as string,
      currency: params.currency as pumpfun.AthCurrency | undefined,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  "ath-batch": (client, { body }) =>
    client.pumpfun.athBatch({
      mints: body.mints as string[],
    }),
  "ban-status": (client, { params }) =>
    client.pumpfun.banStatus({
      address: params.address as string,
    }),
  "bounty-feed-recent": (client, { params }) =>
    client.pumpfun.bountyFeedRecent({
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "bounty-feed-trending": (client, { params }) =>
    client.pumpfun.bountyFeedTrending({
      limit: params.limit as number | undefined,
    }),
  "bounty-recent-payouts": (client, { params }) =>
    client.pumpfun.bountyRecentPayouts({
      limit: params.limit as number | undefined,
    }),
  "bounty-stats": (client) =>
    client.pumpfun.bountyStats(),
  "bounty-submission-count": (client) =>
    client.pumpfun.bountySubmissionCount(),
  "bounty-submissions": (client, { params }) =>
    client.pumpfun.bountySubmissions({
      requester_address: params.requester_address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "bounty-tasks": (client, { params }) =>
    client.pumpfun.bountyTasks({
      phase: params.phase as pumpfun.BountyPhase[] | undefined,
      sort: params.sort as pumpfun.BountySort | undefined,
      order: params.order as pumpfun.OrderDirection | undefined,
      limit: params.limit as number | undefined,
      facets: params.facets as boolean | undefined,
      coin_address: params.coin_address as (string | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
      q: params.q as (string | null) | undefined,
      creator_address: params.creator_address as (string | null) | undefined,
      reward_mints: params.reward_mints as (string[] | null) | undefined,
      reward_total_usd_gte: params.reward_total_usd_gte as (number | null) | undefined,
      reward_total_usd_lte: params.reward_total_usd_lte as (number | null) | undefined,
      expires_at_gte: params.expires_at_gte as (string | null) | undefined,
      expires_at_lte: params.expires_at_lte as (string | null) | undefined,
      like_count_gte: params.like_count_gte as (number | null) | undefined,
      submission_count_gte: params.submission_count_gte as (number | null) | undefined,
      include_banned: params.include_banned as (boolean | null) | undefined,
      lat: params.lat as (number | null) | undefined,
      lng: params.lng as (number | null) | undefined,
      radius_km: params.radius_km as (number | null) | undefined,
    }),
  "bounty-top-coins": (client, { params }) =>
    client.pumpfun.bountyTopCoins({
      limit: params.limit as number | undefined,
    }),
  "bounty-top-earners": (client, { params }) =>
    client.pumpfun.bountyTopEarners({
      limit: params.limit as number | undefined,
    }),
  "bounty-top-spenders": (client, { params }) =>
    client.pumpfun.bountyTopSpenders({
      limit: params.limit as number | undefined,
    }),
  callout: (client, { params }) =>
    client.pumpfun.callout({
      callout_id: params.callout_id as string,
    }),
  "callout-leaderboard-stats": (client, { params }) =>
    client.pumpfun.calloutLeaderboardStats({
      address: params.address as string,
    }),
  "callout-likers": (client, { params }) =>
    client.pumpfun.calloutLikers({
      callout_id: params.callout_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "callout-quotes": (client, { params }) =>
    client.pumpfun.calloutQuotes({
      callout_id: params.callout_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "callout-replies": (client, { params }) =>
    client.pumpfun.calloutReplies({
      callout_id: params.callout_id as string,
      limit: params.limit as number | undefined,
      filter: params.filter as pumpfun.ReplyFilter | undefined,
      before_id: params.before_id as (string | null) | undefined,
      page: params.page as (number | null) | undefined,
      sort: params.sort as (pumpfun.ReplySort | null) | undefined,
      parent_reply_id: params.parent_reply_id as (string | null) | undefined,
      nested_limit: params.nested_limit as (number | null) | undefined,
    }),
  "callout-reposters": (client, { params }) =>
    client.pumpfun.calloutReposters({
      callout_id: params.callout_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "callout-stats": (client, { params }) =>
    client.pumpfun.calloutStats({
      address: params.address as string,
    }),
  candles: (client, { params }) =>
    client.pumpfun.candles({
      mint: params.mint as string,
      created_ts: params.created_ts as number,
      interval: params.interval as pumpfun.CandleInterval | undefined,
      limit: params.limit as number | undefined,
      currency: params.currency as pumpfun.AthCurrency | undefined,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  "chain-candles": (client, { params }) =>
    client.pumpfun.chainCandles({
      chain: params.chain as pumpfun.MarketChain,
      address: params.address as string,
      resolution: params.resolution as pumpfun.CandleResolution,
      measure: params.measure as pumpfun.PriceMeasure | undefined,
      to: params.to as (number | null) | undefined,
      count: params.count as number | undefined,
      pool: params.pool as (string | null) | undefined,
    }),
  "chain-price-line": (client, { params }) =>
    client.pumpfun.chainPriceLine({
      chain: params.chain as pumpfun.MarketChain,
      address: params.address as string,
      resolution: params.resolution as pumpfun.CandleResolution,
      measure: params.measure as pumpfun.PriceMeasure | undefined,
      to: params.to as (number | null) | undefined,
      count: params.count as number | undefined,
      max_points: params.max_points as number | undefined,
    }),
  "chain-top-holders": (client, { params }) =>
    client.pumpfun.chainTopHolders({
      chain: params.chain as pumpfun.TokenChain,
      address: params.address as string,
    }),
  "chain-trades": (client, { params }) =>
    client.pumpfun.chainTrades({
      chain: params.chain as pumpfun.MarketChain,
      address: params.address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
      before: params.before as (string | null) | undefined,
      after: params.after as (string | null) | undefined,
      kinds: params.kinds as (pumpfun.TradeKind[] | null) | undefined,
      min_usd: params.min_usd as (number | null) | undefined,
      pool: params.pool as (string | null) | undefined,
      venue: params.venue as pumpfun.TradeVenue | undefined,
    }),
  "clip-counts": (client, { params }) =>
    client.pumpfun.clipCounts({
      mint: params.mint as string,
    }),
  "clips-batch": (client, { body }) =>
    client.pumpfun.clipsBatch({
      clips: body.clips as pumpfun.ClipReferenceRequest[],
    }),
  coin: (client, { params }) =>
    client.pumpfun.coin({
      mint: params.mint as string,
      include_livestream_info: params.include_livestream_info as boolean | undefined,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  "coin-board": (client, { params }) =>
    client.pumpfun.coinBoard({
      board: params.board as pumpfun.CoinBoard,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
      chains: params.chains as (pumpfun.TokenChain[] | null) | undefined,
    }),
  "coin-clips": (client, { params }) =>
    client.pumpfun.coinClips({
      mint: params.mint as string,
      clip_type: params.clip_type as string | undefined,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "coin-fee-events": (client, { params }) =>
    client.pumpfun.coinFeeEvents({
      chain: params.chain as pumpfun.TokenChain,
      address: params.address as string,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "coin-holder-pnl": (client, { params, body }) =>
    client.pumpfun.coinHolderPnl({
      mint: params.mint as string,
    }, {
      holders: body.holders as string[],
    }),
  "coin-mayhem-state": (client, { params }) =>
    client.pumpfun.coinMayhemState({
      mint: params.mint as string,
    }),
  "coin-narratives": (client, { params }) =>
    client.pumpfun.coinNarratives({
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
      source: params.source as (pumpfun.NarrativeSource | null) | undefined,
      locale: params.locale as (string | null) | undefined,
    }),
  "coin-timeline": (client, { params }) =>
    client.pumpfun.coinTimeline({
      mint: params.mint as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "coin-top-callouts": (client, { params }) =>
    client.pumpfun.coinTopCallouts({
      mint: params.mint as string,
      limit: params.limit as number | undefined,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  coins: (client, { params }) =>
    client.pumpfun.coins({
      offset: params.offset as number | undefined,
      limit: params.limit as number | undefined,
      sort: params.sort as pumpfun.CoinSort | undefined,
      order: params.order as pumpfun.CoinSortDirection | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
      creator: params.creator as (string | null) | undefined,
      complete: params.complete as (boolean | null) | undefined,
      boost_modes: params.boost_modes as (pumpfun.BoostMode[] | null) | undefined,
    }),
  "coins-batch": (client, { body }) =>
    client.pumpfun.coinsBatch({
      include_nsfw: body.include_nsfw as boolean | undefined,
      mints: body.mints as string[],
    }),
  "coins-raw-batch": (client, { body }) =>
    client.pumpfun.coinsRawBatch({
      mints: body.mints as string[],
    }),
  competition: (client, { params }) =>
    client.pumpfun.competition({
      competition: params.competition as string,
      limit: params.limit as number | undefined,
      positions_limit: params.positions_limit as number | undefined,
    }),
  "competition-entry": (client, { params }) =>
    client.pumpfun.competitionEntry({
      competition_id: params.competition_id as string,
      entry_id: params.entry_id as string,
    }),
  "competition-entry-highlights": (client, { params }) =>
    client.pumpfun.competitionEntryHighlights({
      competition_id: params.competition_id as string,
      entry_id: params.entry_id as string,
      limit: params.limit as number | undefined,
    }),
  "competition-highlights": (client, { params }) =>
    client.pumpfun.competitionHighlights({
      competition_id: params.competition_id as string,
      limit: params.limit as number | undefined,
      per_member_limit: params.per_member_limit as number | undefined,
    }),
  competitions: (client) =>
    client.pumpfun.competitions(),
  "creator-fees": (client, { params }) =>
    client.pumpfun.creatorFees({
      address: params.address as string,
      interval: params.interval as pumpfun.CreatorFeeInterval | undefined,
      period: params.period as (pumpfun.FeePeriod | null) | undefined,
      mint: params.mint as (string | null) | undefined,
    }),
  "creator-fees-total": (client, { params }) =>
    client.pumpfun.creatorFeesTotal({
      address: params.address as string,
    }),
  "fee-sharing-shares": (client, { params }) =>
    client.pumpfun.feeSharingShares({
      address: params.address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as string | undefined,
    }),
  "fee-sharing-totals": (client, { params }) =>
    client.pumpfun.feeSharingTotals({
      address: params.address as string,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "first-trade": (client, { params }) =>
    client.pumpfun.firstTrade({
      mint: params.mint as string,
    }),
  "follow-suggestions": (client, { params }) =>
    client.pumpfun.followSuggestions({
      limit: params.limit as number | undefined,
    }),
  followers: (client, { params }) =>
    client.pumpfun.followers({
      address: params.address as string,
      limit: params.limit as (number | null) | undefined,
      offset: params.offset as (number | null) | undefined,
      sort: params.sort as (pumpfun.FollowSort | null) | undefined,
    }),
  "followers-count": (client, { params }) =>
    client.pumpfun.followersCount({
      address: params.address as string,
    }),
  following: (client, { params }) =>
    client.pumpfun.following({
      address: params.address as string,
      limit: params.limit as (number | null) | undefined,
      offset: params.offset as (number | null) | undefined,
      sort: params.sort as (pumpfun.FollowSort | null) | undefined,
    }),
  "following-count": (client, { params }) =>
    client.pumpfun.followingCount({
      address: params.address as string,
    }),
  "global-params": (client, { params }) =>
    client.pumpfun.globalParams({
      params_id: params.params_id as number | undefined,
    }),
  "group-members": (client, { params }) =>
    client.pumpfun.groupMembers({
      group_id: params.group_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "group-members-pnl": (client, { params }) =>
    client.pumpfun.groupMembersPnl({
      group_id: params.group_id as string,
      period: params.period as pumpfun.RollingWindow | undefined,
    }),
  "group-pnl-leaderboard": (client, { params }) =>
    client.pumpfun.groupPnlLeaderboard({
      period: params.period as pumpfun.LeaderboardPeriod | undefined,
      sort: params.sort as (pumpfun.LeaderboardSort | null) | undefined,
      limit: params.limit as number | undefined,
      positions_limit: params.positions_limit as (number | null) | undefined,
    }),
  "holder-rewards": (client, { params }) =>
    client.pumpfun.holderRewards({
      cursor: params.cursor as (string | null) | undefined,
      sort: params.sort as pumpfun.HolderRewardSort | undefined,
      direction: params.direction as pumpfun.OrderDirection | undefined,
      quote: params.quote as (string | null) | undefined,
      paying_only: params.paying_only as (boolean | null) | undefined,
      page: params.page as number | undefined,
      limit: params.limit as number | undefined,
    }),
  "holder-stats": (client, { params }) =>
    client.pumpfun.holderStats({
      mint: params.mint as string,
    }),
  "home-feed": (client, { params }) =>
    client.pumpfun.homeFeed({
      page_size: params.page_size as number | undefined,
      chain: params.chain as pumpfun.FeedChain | undefined,
      page: params.page as (number | null) | undefined,
      updates_limit: params.updates_limit as (number | null) | undefined,
    }),
  "hot-coin": (client) =>
    client.pumpfun.hotCoin(),
  "in-memory-coin": (client, { params }) =>
    client.pumpfun.inMemoryCoin({
      mint: params.mint as string,
    }),
  "line-chart": (client, { params }) =>
    client.pumpfun.lineChart({
      mint: params.mint as string,
      created_ts: params.created_ts as number,
      timeframe: params.timeframe as pumpfun.ChartTimeframe | undefined,
      width: params.width as number | undefined,
    }),
  "live-coins": (client, { params }) =>
    client.pumpfun.liveCoins({
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
    }),
  livestream: (client, { params }) =>
    client.pumpfun.livestream({
      mint: params.mint as string,
    }),
  "livestream-history": (client, { params }) =>
    client.pumpfun.livestreamHistory({
      mint: params.mint as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "market-activity": (client, { params }) =>
    client.pumpfun.marketActivity({
      mint: params.mint as string,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  "market-activity-batch": (client, { body }) =>
    client.pumpfun.marketActivityBatch({
      intervals: body.intervals as (pumpfun.MarketActivityInterval[] | null) | undefined,
      metrics: body.metrics as (pumpfun.MarketActivityMetric[] | null) | undefined,
      mints: body.mints as string[],
    }),
  "mayhem-coin-top-traders": (client, { params }) =>
    client.pumpfun.mayhemCoinTopTraders({
      mint: params.mint as string,
    }),
  "mayhem-coins": (client, { params }) =>
    client.pumpfun.mayhemCoins({
      limit: params.limit as number | undefined,
      mayhem_state: params.mayhem_state as (pumpfun.MayhemState | null) | undefined,
      offset: params.offset as (number | null) | undefined,
      include_nsfw: params.include_nsfw as (boolean | null) | undefined,
    }),
  "mayhem-overview": (client) =>
    client.pumpfun.mayhemOverview(),
  "mayhem-stats": (client, { params }) =>
    client.pumpfun.mayhemStats({
      mint: params.mint as string,
    }),
  "mayhem-top-coins": (client, { params }) =>
    client.pumpfun.mayhemTopCoins({
      window: params.window as pumpfun.MayhemWindow | undefined,
    }),
  "mayhem-top-traders": (client, { params }) =>
    client.pumpfun.mayhemTopTraders({
      window: params.window as pumpfun.MayhemWindow | undefined,
    }),
  "mint-positions": (client, { params }) =>
    client.pumpfun.mintPositions({
      mint: params.mint as string,
      page_size: params.page_size as number | undefined,
      sort_by: params.sort_by as pumpfun.MintPositionSort | undefined,
      with_thesis: params.with_thesis as (boolean | null) | undefined,
      page: params.page as (number | null) | undefined,
      updates_limit: params.updates_limit as (number | null) | undefined,
      include_profile: params.include_profile as (boolean | null) | undefined,
      dust_floor_usd: params.dust_floor_usd as (number | null) | undefined,
      page_token: params.page_token as (string | null) | undefined,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
    }),
  "movers-board": (client, { params }) =>
    client.pumpfun.moversBoard({
      limit: params.limit as number | undefined,
      chains: params.chains as (pumpfun.NonMonadChain[] | null) | undefined,
    }),
  "new-callouts-count": (client, { params }) =>
    client.pumpfun.newCalloutsCount({
      since: params.since as string,
      chain: params.chain as pumpfun.FeedChain | undefined,
      min_cost_basis_usd: params.min_cost_basis_usd as (number | null) | undefined,
      max_cost_basis_usd: params.max_cost_basis_usd as (number | null) | undefined,
      min_callout_market_cap_usd: params.min_callout_market_cap_usd as (number | null) | undefined,
      max_callout_market_cap_usd: params.max_callout_market_cap_usd as (number | null) | undefined,
      min_market_cap_usd: params.min_market_cap_usd as (number | null) | undefined,
      max_market_cap_usd: params.max_market_cap_usd as (number | null) | undefined,
    }),
  "new-callouts-feed": (client, { params }) =>
    client.pumpfun.newCalloutsFeed({
      page_size: params.page_size as number | undefined,
      page_token: params.page_token as (string | null) | undefined,
      updates_limit: params.updates_limit as (number | null) | undefined,
      chain: params.chain as pumpfun.FeedChain | undefined,
      min_cost_basis_usd: params.min_cost_basis_usd as (number | null) | undefined,
      max_cost_basis_usd: params.max_cost_basis_usd as (number | null) | undefined,
      min_callout_market_cap_usd: params.min_callout_market_cap_usd as (number | null) | undefined,
      max_callout_market_cap_usd: params.max_callout_market_cap_usd as (number | null) | undefined,
      min_market_cap_usd: params.min_market_cap_usd as (number | null) | undefined,
      max_market_cap_usd: params.max_market_cap_usd as (number | null) | undefined,
    }),
  "onboarding-suggestions": (client, { params }) =>
    client.pumpfun.onboardingSuggestions({
      limit: params.limit as number | undefined,
    }),
  "payouts-leaderboard": (client, { params }) =>
    client.pumpfun.payoutsLeaderboard({
      page: params.page as number | undefined,
      page_size: params.page_size as number | undefined,
      period: params.period as (pumpfun.RollingWindow | null) | undefined,
    }),
  "perp-orders": (client, { params }) =>
    client.pumpfun.perpOrders({
      address: params.address as string,
      dex: params.dex as (string[] | null) | undefined,
    }),
  "perp-trades": (client, { params }) =>
    client.pumpfun.perpTrades({
      address: params.address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
      kinds: params.kinds as (pumpfun.PerpTradeKind[] | null) | undefined,
    }),
  perps: (client, { params }) =>
    client.pumpfun.perps({
      sort: params.sort as pumpfun.PerpSort | undefined,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "playlist-map": (client, { body }) =>
    client.pumpfun.playlistMap({
      mints: body.mints as string[],
    }),
  "pnl-leaderboard": (client, { params }) =>
    client.pumpfun.pnlLeaderboard({
      period: params.period as pumpfun.LeaderboardPeriod | undefined,
      sort: params.sort as pumpfun.LeaderboardSort | undefined,
      limit: params.limit as number | undefined,
      positions_limit: params.positions_limit as (number | null) | undefined,
    }),
  "pnl-leaderboard-positions": (client, { params }) =>
    client.pumpfun.pnlLeaderboardPositions({
      period: params.period as pumpfun.PositionsPeriod | undefined,
      limit: params.limit as (number | null) | undefined,
    }),
  "portfolio-summary": (client, { params }) =>
    client.pumpfun.portfolioSummary({
      address: params.address as string,
      period: params.period as pumpfun.PortfolioPeriod | undefined,
    }),
  "portfolio-value-chart": (client, { params }) =>
    client.pumpfun.portfolioValueChart({
      address: params.address as string,
      period: params.period as pumpfun.RollingWindow | undefined,
    }),
  "reply-likers": (client, { params }) =>
    client.pumpfun.replyLikers({
      reply_id: params.reply_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "reply-reposters": (client, { params }) =>
    client.pumpfun.replyReposters({
      reply_id: params.reply_id as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "reply-thread": (client, { params }) =>
    client.pumpfun.replyThread({
      reply_id: params.reply_id as string,
    }),
  "resolve-identifiers": (client, { params }) =>
    client.pumpfun.resolveIdentifiers({
      identifiers: params.identifiers as string[],
    }),
  "search-coins": (client, { params }) =>
    client.pumpfun.searchCoins({
      search_term: params.search_term as string,
      offset: params.offset as number | undefined,
      limit: params.limit as number | undefined,
      sort: params.sort as pumpfun.CoinSort | undefined,
      order: params.order as pumpfun.CoinSortDirection | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
      creator: params.creator as (string | null) | undefined,
      complete: params.complete as (boolean | null) | undefined,
      min_age_seconds: params.min_age_seconds as (number | null) | undefined,
      max_age_seconds: params.max_age_seconds as (number | null) | undefined,
    }),
  "search-followers": (client, { params }) =>
    client.pumpfun.searchFollowers({
      address: params.address as string,
      search_term: params.search_term as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "search-following": (client, { params }) =>
    client.pumpfun.searchFollowing({
      address: params.address as string,
      search_term: params.search_term as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
    }),
  "search-quote-facets": (client, { params }) =>
    client.pumpfun.searchQuoteFacets({
      search_term: params.search_term as (string | null) | undefined,
      creator: params.creator as (string | null) | undefined,
      complete: params.complete as (boolean | null) | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
      min_age_seconds: params.min_age_seconds as (number | null) | undefined,
      max_age_seconds: params.max_age_seconds as (number | null) | undefined,
    }),
  "search-users": (client, { params }) =>
    client.pumpfun.searchUsers({
      search_term: params.search_term as string,
      offset: params.offset as number | undefined,
      limit: params.limit as number | undefined,
      include_labelled_wallets: params.include_labelled_wallets as boolean | undefined,
    }),
  "shareholder-fees": (client, { params }) =>
    client.pumpfun.shareholderFees({
      address: params.address as string,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "similar-coins": (client, { params }) =>
    client.pumpfun.similarCoins({
      mint: params.mint as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
    }),
  "sol-price": (client) =>
    client.pumpfun.solPrice(),
  "token-holder-count": (client, { params }) =>
    client.pumpfun.tokenHolderCount({
      mint: params.mint as string,
    }),
  "top-clips": (client, { params }) =>
    client.pumpfun.topClips({
      period: params.period as pumpfun.VodPeriod | undefined,
      limit: params.limit as number | undefined,
      oversample: params.oversample as number | undefined,
      clip_type: params.clip_type as pumpfun.ClipType | undefined,
      timestamp: params.timestamp as (number | null) | undefined,
    }),
  "top-holders": (client, { params }) =>
    client.pumpfun.topHolders({
      mint: params.mint as string,
    }),
  "top-profiles": (client) =>
    client.pumpfun.topProfiles(),
  "top-token-mint-chains": (client, { params }) =>
    client.pumpfun.topTokenMintChains({
      sort_order: params.sort_order as (pumpfun.TopMintsSort | null) | undefined,
    }),
  "top-token-mints": (client, { params }) =>
    client.pumpfun.topTokenMints({
      sort_order: params.sort_order as (pumpfun.TopMintsSort | null) | undefined,
    }),
  "top-trader-trades": (client, { params }) =>
    client.pumpfun.topTraderTrades({
      mint: params.mint as string,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
      to: params.to as (number | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
      limit: params.limit as number | undefined,
    }),
  trades: (client, { params }) =>
    client.pumpfun.trades({
      mint: params.mint as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
      min_sol_amount: params.min_sol_amount as (number | null) | undefined,
    }),
  "trades-batch": (client, { params, body }) =>
    client.pumpfun.tradesBatch({
      mint: params.mint as string,
    }, {
      created_ts: body.created_ts as number,
      user_addresses: body.user_addresses as string[],
    }),
  "trending-board": (client, { params }) =>
    client.pumpfun.trendingBoard({
      limit: params.limit as number | undefined,
      chains: params.chains as (pumpfun.NonMonadChain[] | null) | undefined,
    }),
  "trending-coins": (client, { params }) =>
    client.pumpfun.trendingCoins({
      top_k: params.top_k as number | undefined,
    }),
  user: (client, { params }) =>
    client.pumpfun.user({
      address: params.address as string,
    }),
  "user-achievements": (client, { params }) =>
    client.pumpfun.userAchievements({
      address: params.address as string,
    }),
  "user-callout-replies": (client, { params }) =>
    client.pumpfun.userCalloutReplies({
      address: params.address as string,
      limit: params.limit as number | undefined,
      before_id: params.before_id as (string | null) | undefined,
      filter: params.filter as (pumpfun.UserReplyFilter | null) | undefined,
    }),
  "user-callouts": (client, { params }) =>
    client.pumpfun.userCallouts({
      address: params.address as string,
      limit: params.limit as number | undefined,
      sort_by: params.sort_by as pumpfun.CalloutSort | undefined,
      sort_order: params.sort_order as pumpfun.CoinSortDirection | undefined,
      page_token: params.page_token as (string | null) | undefined,
      window: params.window as (pumpfun.CalloutWindow | null) | undefined,
    }),
  "user-coin-callout": (client, { params }) =>
    client.pumpfun.userCoinCallout({
      address: params.address as string,
      mint: params.mint as string,
      quotes_limit: params.quotes_limit as (number | null) | undefined,
    }),
  "user-created-coins": (client, { params }) =>
    client.pumpfun.userCreatedCoins({
      address: params.address as string,
      limit: params.limit as number | undefined,
      offset: params.offset as number | undefined,
      include_nsfw: params.include_nsfw as boolean | undefined,
    }),
  "user-overview": (client, { params }) =>
    client.pumpfun.userOverview({
      address: params.address as string,
    }),
  "user-portfolio": (client, { params }) =>
    client.pumpfun.userPortfolio({
      address: params.address as string,
      filter: params.filter as pumpfun.PortfolioFilter | undefined,
      page: params.page as number | undefined,
      page_size: params.page_size as number | undefined,
      sort_by: params.sort_by as pumpfun.PortfolioSort | undefined,
      total_only: params.total_only as (boolean | null) | undefined,
      filter_spam: params.filter_spam as (boolean | null) | undefined,
      spam_only: params.spam_only as (boolean | null) | undefined,
      chain: params.chain as (pumpfun.NonMonadChain | null) | undefined,
    }),
  "user-positions": (client, { params }) =>
    client.pumpfun.userPositions({
      address: params.address as string,
      mints: params.mints as string[],
      updates_limit: params.updates_limit as number | undefined,
    }),
  "user-reposts": (client, { params }) =>
    client.pumpfun.userReposts({
      address: params.address as string,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
      include_quotes: params.include_quotes as boolean | undefined,
    }),
  "user-trades": (client, { params }) =>
    client.pumpfun.userTrades({
      address: params.address as string,
      mint: params.mint as (string | null) | undefined,
      chain: params.chain as (pumpfun.NonMonadChain | null) | undefined,
      cursor: params.cursor as (string | null) | undefined,
      limit: params.limit as number | undefined,
      types: params.types as (pumpfun.UserTradeType[] | null) | undefined,
    }),
  "username-exists": (client, { params }) =>
    client.pumpfun.usernameExists({
      username: params.username as string,
    }),
  users: (client, { params }) =>
    client.pumpfun.users({
      offset: params.offset as number | undefined,
      limit: params.limit as number | undefined,
    }),
  "users-batch": (client, { body }) =>
    client.pumpfun.usersBatch({
      addresses: body.addresses as string[],
    }),
  "vanity-check": (client, { params }) =>
    client.pumpfun.vanityCheck({
      mint: params.mint as string,
    }),
  "verified-profiles": (client, { body }) =>
    client.pumpfun.verifiedProfiles({
      ids: body.ids as string[],
    }),
  "video-feed": (client) =>
    client.pumpfun.videoFeed(),
  "wallet-balance-summary": (client, { params }) =>
    client.pumpfun.walletBalanceSummary({
      address: params.address as string,
      multi_chain: params.multi_chain as boolean | undefined,
    }),
  "wallet-balances": (client, { params }) =>
    client.pumpfun.walletBalances({
      address: params.address as string,
      page: params.page as number | undefined,
      size: params.size as number | undefined,
      chain: params.chain as (pumpfun.BalanceChain | null) | undefined,
    }),
  "wallet-overview": (client, { body }) =>
    client.pumpfun.walletOverview({
      wallets: body.wallets as string[],
    }),
  "wallet-pnl-batch": (client, { params, body }) =>
    client.pumpfun.walletPnlBatch({
      address: params.address as string,
    }, {
      mints: body.mints as string[],
    }),
  "wallet-screening": (client, { params }) =>
    client.pumpfun.walletScreening({
      address: params.address as string,
    }),
  "wallet-token-pnl": (client, { params }) =>
    client.pumpfun.walletTokenPnl({
      address: params.address as string,
      mint: params.mint as string,
    }),
  "wallet-trades": (client, { params }) =>
    client.pumpfun.walletTrades({
      address: params.address as string,
      mint: params.mint as string,
      chain: params.chain as (pumpfun.TokenChain | null) | undefined,
      limit: params.limit as number | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
  "wallet-transactions": (client, { params }) =>
    client.pumpfun.walletTransactions({
      address: params.address as string,
      dust_filter: params.dust_filter as boolean | undefined,
      include_evm: params.include_evm as boolean | undefined,
      cursor: params.cursor as (string | null) | undefined,
    }),
};

export const COMMAND_LIST: Command[] = COMMANDS.map((spec) => ({ ...spec, run: RUNNERS[spec.name] }));
